services:

  frontend:
    build: ./frontend
    container_name: site-jo
    ports:
      - 5555:5173
    volumes:
      - "./frontend/app:/app"
      - "node_modules:/app/node_modules"
    restart: unless-stopped

volumes:
  node_modules: